import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent

load_dotenv(BASE_DIR / ".env")

BOT_TOKEN = os.getenv("BOT_TOKEN")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD")
MASTER_ADMIN_ID = int(os.getenv("MASTER_ADMIN_ID"))
SUPPORT_BOT_TOKEN = os.getenv("SUPPORT_BOT_TOKEN")
SUPPORT_CHAT_ID = int(os.getenv("SUPPORT_CHAT_ID"))
PAYMENT_PROVIDER_TOKEN = os.getenv("PAYMENT_PROVIDER_TOKEN")

# ===== Robokassa =====
ROBOKASSA_LOGIN = os.getenv("ROBOKASSA_LOGIN", "").strip()

ROBOKASSA_IS_TEST = os.getenv("ROBOKASSA_IS_TEST", "0").strip().lower() in (
    "1",
    "true",
    "yes",
)

ROBOKASSA_PASSWORD1_PROD = os.getenv("ROBOKASSA_PASSWORD1", "").strip()
ROBOKASSA_PASSWORD2_PROD = os.getenv("ROBOKASSA_PASSWORD2", "").strip()

ROBOKASSA_PASSWORD1_TEST = os.getenv("ROBOKASSA_TEST_PASSWORD1", "").strip()
ROBOKASSA_PASSWORD2_TEST = os.getenv("ROBOKASSA_TEST_PASSWORD2", "").strip()

ROBOKASSA_PASSWORD1 = ROBOKASSA_PASSWORD1_TEST if ROBOKASSA_IS_TEST else ROBOKASSA_PASSWORD1_PROD
ROBOKASSA_PASSWORD2 = ROBOKASSA_PASSWORD2_TEST if ROBOKASSA_IS_TEST else ROBOKASSA_PASSWORD2_PROD

HELP_TELEGRAPH_URL = os.getenv("HELP_TELEGRAPH_URL")
SUPPORT_URL = os.getenv("SUPPORT_URL")